acceleration: 0
angular_velocity: 1
contour: 4
lag: 5
num parameters: 53
reference_velocity: 3
spline0_start: 16
spline1_start: 25
spline2_start: 34
spline3_start: 43
spline4_start: 52
spline_x0_a: 8
spline_x0_b: 9
spline_x0_c: 10
spline_x0_d: 11
spline_x1_a: 17
spline_x1_b: 18
spline_x1_c: 19
spline_x1_d: 20
spline_x2_a: 26
spline_x2_b: 27
spline_x2_c: 28
spline_x2_d: 29
spline_x3_a: 35
spline_x3_b: 36
spline_x3_c: 37
spline_x3_d: 38
spline_x4_a: 44
spline_x4_b: 45
spline_x4_c: 46
spline_x4_d: 47
spline_y0_a: 12
spline_y0_b: 13
spline_y0_c: 14
spline_y0_d: 15
spline_y1_a: 21
spline_y1_b: 22
spline_y1_c: 23
spline_y1_d: 24
spline_y2_a: 30
spline_y2_b: 31
spline_y2_c: 32
spline_y2_d: 33
spline_y3_a: 39
spline_y3_b: 40
spline_y3_c: 41
spline_y3_d: 42
spline_y4_a: 48
spline_y4_b: 49
spline_y4_c: 50
spline_y4_d: 51
terminal_angle: 6
terminal_contouring: 7
velocity: 2
