/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[33] = {5, 5, 0, 5, 10, 15, 20, 25, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[15] = {5, 2, 0, 5, 10, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s4[57] = {53, 1, 0, 53, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52};
static const casadi_int casadi_s5[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s6[32] = {28, 1, 0, 28, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};

/* Solver_expl_ode_hess:(i0[5],i1[5x5],i2[5x2],i3[5],i4[2],i5[53])->(o0[7],o1[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=arg[3]? arg[3][1] : 0;
  a5=(a3*a4);
  a6=(a2*a5);
  a7=sin(a1);
  a8=arg[3]? arg[3][0] : 0;
  a3=(a3*a8);
  a9=(a7*a3);
  a6=(a6-a9);
  if (res[0]!=0) res[0][2]=a6;
  a6=arg[3]? arg[3][4] : 0;
  a9=sin(a1);
  a9=(a9*a4);
  a6=(a6+a9);
  a9=cos(a1);
  a9=(a9*a8);
  a6=(a6+a9);
  if (res[0]!=0) res[0][3]=a6;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a6=arg[1]? arg[1][3] : 0;
  a9=(a4*a6);
  a9=(a2*a9);
  a10=sin(a1);
  a11=(a10*a0);
  a11=(a5*a11);
  a9=(a9-a11);
  a11=cos(a1);
  a12=(a11*a0);
  a12=(a3*a12);
  a13=(a8*a6);
  a13=(a7*a13);
  a12=(a12+a13);
  a9=(a9-a12);
  a12=(a0*a9);
  a13=cos(a1);
  a14=(a13*a0);
  a14=(a4*a14);
  a1=sin(a1);
  a0=(a1*a0);
  a0=(a8*a0);
  a14=(a14-a0);
  a6=(a6*a14);
  a12=(a12+a6);
  if (res[1]!=0) res[1][0]=a12;
  a12=arg[1]? arg[1][7] : 0;
  a6=(a12*a9);
  a0=arg[1]? arg[1][8] : 0;
  a15=(a0*a14);
  a6=(a6+a15);
  if (res[1]!=0) res[1][1]=a6;
  a6=arg[1]? arg[1][12] : 0;
  a15=(a6*a9);
  a16=arg[1]? arg[1][13] : 0;
  a17=(a16*a14);
  a15=(a15+a17);
  if (res[1]!=0) res[1][2]=a15;
  a15=arg[1]? arg[1][17] : 0;
  a17=(a15*a9);
  a18=arg[1]? arg[1][18] : 0;
  a19=(a18*a14);
  a17=(a17+a19);
  if (res[1]!=0) res[1][3]=a17;
  a17=arg[1]? arg[1][22] : 0;
  a19=(a17*a9);
  a20=arg[1]? arg[1][23] : 0;
  a21=(a20*a14);
  a19=(a19+a21);
  if (res[1]!=0) res[1][4]=a19;
  a19=arg[2]? arg[2][2] : 0;
  a21=(a19*a9);
  a22=arg[2]? arg[2][3] : 0;
  a23=(a22*a14);
  a21=(a21+a23);
  if (res[1]!=0) res[1][5]=a21;
  a21=arg[2]? arg[2][7] : 0;
  a9=(a21*a9);
  a23=arg[2]? arg[2][8] : 0;
  a14=(a23*a14);
  a9=(a9+a14);
  if (res[1]!=0) res[1][6]=a9;
  a9=(a4*a0);
  a9=(a2*a9);
  a14=(a10*a12);
  a14=(a5*a14);
  a9=(a9-a14);
  a14=(a11*a12);
  a14=(a3*a14);
  a24=(a8*a0);
  a24=(a7*a24);
  a14=(a14+a24);
  a9=(a9-a14);
  a14=(a12*a9);
  a24=(a13*a12);
  a24=(a4*a24);
  a12=(a1*a12);
  a12=(a8*a12);
  a24=(a24-a12);
  a0=(a0*a24);
  a14=(a14+a0);
  if (res[1]!=0) res[1][7]=a14;
  a14=(a6*a9);
  a0=(a16*a24);
  a14=(a14+a0);
  if (res[1]!=0) res[1][8]=a14;
  a14=(a15*a9);
  a0=(a18*a24);
  a14=(a14+a0);
  if (res[1]!=0) res[1][9]=a14;
  a14=(a17*a9);
  a0=(a20*a24);
  a14=(a14+a0);
  if (res[1]!=0) res[1][10]=a14;
  a14=(a19*a9);
  a0=(a22*a24);
  a14=(a14+a0);
  if (res[1]!=0) res[1][11]=a14;
  a9=(a21*a9);
  a24=(a23*a24);
  a9=(a9+a24);
  if (res[1]!=0) res[1][12]=a9;
  a9=(a4*a16);
  a9=(a2*a9);
  a24=(a10*a6);
  a24=(a5*a24);
  a9=(a9-a24);
  a24=(a11*a6);
  a24=(a3*a24);
  a14=(a8*a16);
  a14=(a7*a14);
  a24=(a24+a14);
  a9=(a9-a24);
  a24=(a6*a9);
  a14=(a13*a6);
  a14=(a4*a14);
  a6=(a1*a6);
  a6=(a8*a6);
  a14=(a14-a6);
  a16=(a16*a14);
  a24=(a24+a16);
  if (res[1]!=0) res[1][13]=a24;
  a24=(a15*a9);
  a16=(a18*a14);
  a24=(a24+a16);
  if (res[1]!=0) res[1][14]=a24;
  a24=(a17*a9);
  a16=(a20*a14);
  a24=(a24+a16);
  if (res[1]!=0) res[1][15]=a24;
  a24=(a19*a9);
  a16=(a22*a14);
  a24=(a24+a16);
  if (res[1]!=0) res[1][16]=a24;
  a9=(a21*a9);
  a14=(a23*a14);
  a9=(a9+a14);
  if (res[1]!=0) res[1][17]=a9;
  a9=(a4*a18);
  a9=(a2*a9);
  a14=(a10*a15);
  a14=(a5*a14);
  a9=(a9-a14);
  a14=(a11*a15);
  a14=(a3*a14);
  a24=(a8*a18);
  a24=(a7*a24);
  a14=(a14+a24);
  a9=(a9-a14);
  a14=(a15*a9);
  a24=(a13*a15);
  a24=(a4*a24);
  a15=(a1*a15);
  a15=(a8*a15);
  a24=(a24-a15);
  a18=(a18*a24);
  a14=(a14+a18);
  if (res[1]!=0) res[1][18]=a14;
  a14=(a17*a9);
  a18=(a20*a24);
  a14=(a14+a18);
  if (res[1]!=0) res[1][19]=a14;
  a14=(a19*a9);
  a18=(a22*a24);
  a14=(a14+a18);
  if (res[1]!=0) res[1][20]=a14;
  a9=(a21*a9);
  a24=(a23*a24);
  a9=(a9+a24);
  if (res[1]!=0) res[1][21]=a9;
  a9=(a4*a20);
  a9=(a2*a9);
  a24=(a10*a17);
  a24=(a5*a24);
  a9=(a9-a24);
  a24=(a11*a17);
  a24=(a3*a24);
  a14=(a8*a20);
  a14=(a7*a14);
  a24=(a24+a14);
  a9=(a9-a24);
  a24=(a17*a9);
  a14=(a13*a17);
  a14=(a4*a14);
  a17=(a1*a17);
  a17=(a8*a17);
  a14=(a14-a17);
  a20=(a20*a14);
  a24=(a24+a20);
  if (res[1]!=0) res[1][22]=a24;
  a24=(a19*a9);
  a20=(a22*a14);
  a24=(a24+a20);
  if (res[1]!=0) res[1][23]=a24;
  a9=(a21*a9);
  a14=(a23*a14);
  a9=(a9+a14);
  if (res[1]!=0) res[1][24]=a9;
  a9=(a4*a22);
  a9=(a2*a9);
  a14=(a10*a19);
  a14=(a5*a14);
  a9=(a9-a14);
  a14=(a11*a19);
  a14=(a3*a14);
  a24=(a8*a22);
  a24=(a7*a24);
  a14=(a14+a24);
  a9=(a9-a14);
  a14=(a19*a9);
  a24=(a13*a19);
  a24=(a4*a24);
  a19=(a1*a19);
  a19=(a8*a19);
  a24=(a24-a19);
  a22=(a22*a24);
  a14=(a14+a22);
  if (res[1]!=0) res[1][25]=a14;
  a9=(a21*a9);
  a24=(a23*a24);
  a9=(a9+a24);
  if (res[1]!=0) res[1][26]=a9;
  a9=(a4*a23);
  a2=(a2*a9);
  a10=(a10*a21);
  a5=(a5*a10);
  a2=(a2-a5);
  a11=(a11*a21);
  a3=(a3*a11);
  a11=(a8*a23);
  a7=(a7*a11);
  a3=(a3+a7);
  a2=(a2-a3);
  a2=(a21*a2);
  a13=(a13*a21);
  a4=(a4*a13);
  a1=(a1*a21);
  a8=(a8*a1);
  a4=(a4-a8);
  a23=(a23*a4);
  a2=(a2+a23);
  if (res[1]!=0) res[1][27]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int Solver_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Solver_expl_ode_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_ode_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_expl_ode_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s0;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
