/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Solver_cost_ext_cost_0_fun_jac_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[57] = {53, 1, 0, 53, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};

/* Solver_cost_ext_cost_0_fun_jac:(i0[5],i1[2],i2[],i3[53])->(o0,o1[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a14, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a15, a150, a151, a152, a153, a154, a155, a156, a157, a158, a159, a16, a160, a161, a162, a163, a164, a165, a166, a167, a168, a169, a17, a170, a171, a172, a173, a174, a175, a176, a177, a178, a179, a18, a180, a181, a182, a183, a184, a185, a186, a187, a188, a189, a19, a190, a191, a192, a193, a194, a195, a196, a197, a198, a199, a2, a20, a200, a201, a202, a203, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=casadi_sq(a1);
  a2=(a0*a2);
  a3=arg[3]? arg[3][1] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a5=casadi_sq(a4);
  a5=(a3*a5);
  a2=(a2+a5);
  a5=arg[3]? arg[3][2] : 0;
  a6=arg[0]? arg[0][3] : 0;
  a7=arg[3]? arg[3][3] : 0;
  a6=(a6-a7);
  a7=casadi_sq(a6);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=arg[3]? arg[3][5] : 0;
  a8=3.;
  a9=arg[3]? arg[3][8] : 0;
  a10=(a8*a9);
  a11=arg[0]? arg[0][4] : 0;
  a12=arg[3]? arg[3][16] : 0;
  a13=(a11-a12);
  a14=(a10*a13);
  a15=(a14*a13);
  a16=2.;
  a17=arg[3]? arg[3][9] : 0;
  a18=(a16*a17);
  a19=(a18*a13);
  a15=(a15+a19);
  a19=arg[3]? arg[3][10] : 0;
  a15=(a15+a19);
  a20=1.;
  a21=arg[3]? arg[3][25] : 0;
  a22=(a11-a21);
  a23=2.0000000000000000e-02;
  a22=(a22+a23);
  a24=1.0000000000000001e-01;
  a22=(a22/a24);
  a22=exp(a22);
  a25=(a20+a22);
  a15=(a15/a25);
  a26=(1./a25);
  a27=(a20-a26);
  a28=arg[3]? arg[3][17] : 0;
  a29=(a8*a28);
  a30=(a11-a21);
  a31=(a29*a30);
  a32=(a31*a30);
  a33=arg[3]? arg[3][18] : 0;
  a34=(a16*a33);
  a35=(a34*a30);
  a32=(a32+a35);
  a35=arg[3]? arg[3][19] : 0;
  a32=(a32+a35);
  a36=arg[3]? arg[3][34] : 0;
  a37=(a11-a36);
  a37=(a37+a23);
  a37=(a37/a24);
  a37=exp(a37);
  a38=(a20+a37);
  a32=(a32/a38);
  a39=(1./a38);
  a40=(a20-a39);
  a41=arg[3]? arg[3][26] : 0;
  a42=(a8*a41);
  a43=(a11-a36);
  a44=(a42*a43);
  a45=(a44*a43);
  a46=arg[3]? arg[3][27] : 0;
  a47=(a16*a46);
  a48=(a47*a43);
  a45=(a45+a48);
  a48=arg[3]? arg[3][28] : 0;
  a45=(a45+a48);
  a49=arg[3]? arg[3][43] : 0;
  a50=(a11-a49);
  a50=(a50+a23);
  a50=(a50/a24);
  a50=exp(a50);
  a51=(a20+a50);
  a45=(a45/a51);
  a52=(1./a51);
  a53=(a20-a52);
  a54=arg[3]? arg[3][35] : 0;
  a55=(a8*a54);
  a56=(a11-a49);
  a57=(a55*a56);
  a58=(a57*a56);
  a59=arg[3]? arg[3][36] : 0;
  a60=(a16*a59);
  a61=(a60*a56);
  a58=(a58+a61);
  a61=arg[3]? arg[3][37] : 0;
  a58=(a58+a61);
  a62=arg[3]? arg[3][52] : 0;
  a63=(a11-a62);
  a63=(a63+a23);
  a63=(a63/a24);
  a63=exp(a63);
  a64=(a20+a63);
  a58=(a58/a64);
  a65=(1./a64);
  a66=(a20-a65);
  a67=arg[3]? arg[3][44] : 0;
  a68=(a8*a67);
  a69=(a11-a62);
  a70=(a68*a69);
  a71=(a70*a69);
  a72=arg[3]? arg[3][45] : 0;
  a73=(a16*a72);
  a74=(a73*a69);
  a71=(a71+a74);
  a74=arg[3]? arg[3][46] : 0;
  a71=(a71+a74);
  a75=(a66*a71);
  a75=(a58+a75);
  a76=(a53*a75);
  a76=(a45+a76);
  a77=(a40*a76);
  a77=(a32+a77);
  a78=(a27*a77);
  a78=(a15+a78);
  a79=casadi_sq(a78);
  a80=arg[3]? arg[3][12] : 0;
  a81=(a8*a80);
  a82=(a11-a12);
  a83=(a81*a82);
  a84=(a83*a82);
  a85=arg[3]? arg[3][13] : 0;
  a86=(a16*a85);
  a87=(a86*a82);
  a84=(a84+a87);
  a87=arg[3]? arg[3][14] : 0;
  a84=(a84+a87);
  a88=(a11-a21);
  a88=(a88+a23);
  a88=(a88/a24);
  a88=exp(a88);
  a89=(a20+a88);
  a84=(a84/a89);
  a90=(1./a89);
  a91=(a20-a90);
  a92=arg[3]? arg[3][21] : 0;
  a93=(a8*a92);
  a94=(a11-a21);
  a95=(a93*a94);
  a96=(a95*a94);
  a97=arg[3]? arg[3][22] : 0;
  a98=(a16*a97);
  a99=(a98*a94);
  a96=(a96+a99);
  a99=arg[3]? arg[3][23] : 0;
  a96=(a96+a99);
  a100=(a11-a36);
  a100=(a100+a23);
  a100=(a100/a24);
  a100=exp(a100);
  a101=(a20+a100);
  a96=(a96/a101);
  a102=(1./a101);
  a103=(a20-a102);
  a104=arg[3]? arg[3][30] : 0;
  a105=(a8*a104);
  a106=(a11-a36);
  a107=(a105*a106);
  a108=(a107*a106);
  a109=arg[3]? arg[3][31] : 0;
  a110=(a16*a109);
  a111=(a110*a106);
  a108=(a108+a111);
  a111=arg[3]? arg[3][32] : 0;
  a108=(a108+a111);
  a112=(a11-a49);
  a112=(a112+a23);
  a112=(a112/a24);
  a112=exp(a112);
  a113=(a20+a112);
  a108=(a108/a113);
  a114=(1./a113);
  a115=(a20-a114);
  a116=arg[3]? arg[3][39] : 0;
  a117=(a8*a116);
  a118=(a11-a49);
  a119=(a117*a118);
  a120=(a119*a118);
  a121=arg[3]? arg[3][40] : 0;
  a122=(a16*a121);
  a123=(a122*a118);
  a120=(a120+a123);
  a123=arg[3]? arg[3][41] : 0;
  a120=(a120+a123);
  a124=(a11-a62);
  a124=(a124+a23);
  a124=(a124/a24);
  a124=exp(a124);
  a24=(a20+a124);
  a120=(a120/a24);
  a23=(1./a24);
  a125=(a20-a23);
  a126=arg[3]? arg[3][48] : 0;
  a8=(a8*a126);
  a127=(a11-a62);
  a128=(a8*a127);
  a129=(a128*a127);
  a130=arg[3]? arg[3][49] : 0;
  a16=(a16*a130);
  a131=(a16*a127);
  a129=(a129+a131);
  a131=arg[3]? arg[3][50] : 0;
  a129=(a129+a131);
  a132=(a125*a129);
  a132=(a120+a132);
  a133=(a115*a132);
  a133=(a108+a133);
  a134=(a103*a133);
  a134=(a96+a134);
  a135=(a91*a134);
  a135=(a84+a135);
  a136=casadi_sq(a135);
  a79=(a79+a136);
  a79=sqrt(a79);
  a136=(a78/a79);
  a137=arg[0]? arg[0][0] : 0;
  a138=(a11-a12);
  a139=(a9*a138);
  a140=(a139*a138);
  a141=(a140*a138);
  a142=(a17*a138);
  a143=(a142*a138);
  a141=(a141+a143);
  a143=(a19*a138);
  a141=(a141+a143);
  a143=arg[3]? arg[3][11] : 0;
  a141=(a141+a143);
  a141=(a141/a25);
  a143=(a20-a26);
  a144=(a11-a21);
  a145=(a28*a144);
  a146=(a145*a144);
  a147=(a146*a144);
  a148=(a33*a144);
  a149=(a148*a144);
  a147=(a147+a149);
  a149=(a35*a144);
  a147=(a147+a149);
  a149=arg[3]? arg[3][20] : 0;
  a147=(a147+a149);
  a147=(a147/a38);
  a149=(a20-a39);
  a150=(a11-a36);
  a151=(a41*a150);
  a152=(a151*a150);
  a153=(a152*a150);
  a154=(a46*a150);
  a155=(a154*a150);
  a153=(a153+a155);
  a155=(a48*a150);
  a153=(a153+a155);
  a155=arg[3]? arg[3][29] : 0;
  a153=(a153+a155);
  a153=(a153/a51);
  a155=(a20-a52);
  a156=(a11-a49);
  a157=(a54*a156);
  a158=(a157*a156);
  a159=(a158*a156);
  a160=(a59*a156);
  a161=(a160*a156);
  a159=(a159+a161);
  a161=(a61*a156);
  a159=(a159+a161);
  a161=arg[3]? arg[3][38] : 0;
  a159=(a159+a161);
  a159=(a159/a64);
  a161=(a20-a65);
  a162=(a11-a62);
  a163=(a67*a162);
  a164=(a163*a162);
  a165=(a164*a162);
  a166=(a72*a162);
  a167=(a166*a162);
  a165=(a165+a167);
  a167=(a74*a162);
  a165=(a165+a167);
  a167=arg[3]? arg[3][47] : 0;
  a165=(a165+a167);
  a167=(a161*a165);
  a167=(a159+a167);
  a168=(a155*a167);
  a168=(a153+a168);
  a169=(a149*a168);
  a169=(a147+a169);
  a170=(a143*a169);
  a170=(a141+a170);
  a171=(a137-a170);
  a172=(a136*a171);
  a173=(a135/a79);
  a174=arg[0]? arg[0][1] : 0;
  a12=(a11-a12);
  a175=(a80*a12);
  a176=(a175*a12);
  a177=(a176*a12);
  a178=(a85*a12);
  a179=(a178*a12);
  a177=(a177+a179);
  a179=(a87*a12);
  a177=(a177+a179);
  a179=arg[3]? arg[3][15] : 0;
  a177=(a177+a179);
  a177=(a177/a89);
  a179=(a20-a90);
  a21=(a11-a21);
  a180=(a92*a21);
  a181=(a180*a21);
  a182=(a181*a21);
  a183=(a97*a21);
  a184=(a183*a21);
  a182=(a182+a184);
  a184=(a99*a21);
  a182=(a182+a184);
  a184=arg[3]? arg[3][24] : 0;
  a182=(a182+a184);
  a182=(a182/a101);
  a184=(a20-a102);
  a36=(a11-a36);
  a185=(a104*a36);
  a186=(a185*a36);
  a187=(a186*a36);
  a188=(a109*a36);
  a189=(a188*a36);
  a187=(a187+a189);
  a189=(a111*a36);
  a187=(a187+a189);
  a189=arg[3]? arg[3][33] : 0;
  a187=(a187+a189);
  a187=(a187/a113);
  a189=(a20-a114);
  a49=(a11-a49);
  a190=(a116*a49);
  a191=(a190*a49);
  a192=(a191*a49);
  a193=(a121*a49);
  a194=(a193*a49);
  a192=(a192+a194);
  a194=(a123*a49);
  a192=(a192+a194);
  a194=arg[3]? arg[3][42] : 0;
  a192=(a192+a194);
  a192=(a192/a24);
  a20=(a20-a23);
  a11=(a11-a62);
  a62=(a126*a11);
  a194=(a62*a11);
  a195=(a194*a11);
  a196=(a130*a11);
  a197=(a196*a11);
  a195=(a195+a197);
  a197=(a131*a11);
  a195=(a195+a197);
  a197=arg[3]? arg[3][51] : 0;
  a195=(a195+a197);
  a197=(a20*a195);
  a197=(a192+a197);
  a198=(a189*a197);
  a198=(a187+a198);
  a199=(a184*a198);
  a199=(a182+a199);
  a200=(a179*a199);
  a200=(a177+a200);
  a201=(a174-a200);
  a202=(a173*a201);
  a172=(a172+a202);
  a202=casadi_sq(a172);
  a202=(a7*a202);
  a203=arg[3]? arg[3][4] : 0;
  a137=(a137-a170);
  a170=(a173*a137);
  a174=(a174-a200);
  a200=(a136*a174);
  a170=(a170-a200);
  a200=casadi_sq(a170);
  a200=(a203*a200);
  a202=(a202+a200);
  a2=(a2+a202);
  if (res[0]!=0) res[0][0]=a2;
  a1=(a1+a1);
  a1=(a1*a0);
  if (res[1]!=0) res[1][0]=a1;
  a4=(a4+a4);
  a4=(a4*a3);
  if (res[1]!=0) res[1][1]=a4;
  a170=(a170+a170);
  a170=(a170*a203);
  a203=(a173*a170);
  a172=(a172+a172);
  a172=(a172*a7);
  a7=(a136*a172);
  a4=(a203+a7);
  if (res[1]!=0) res[1][2]=a4;
  a4=(a173*a172);
  a3=(a136*a170);
  a1=(a4-a3);
  if (res[1]!=0) res[1][3]=a1;
  a1=0.;
  if (res[1]!=0) res[1][4]=a1;
  a6=(a6+a6);
  a6=(a6*a5);
  if (res[1]!=0) res[1][5]=a6;
  a3=(a3-a4);
  a179=(a179*a3);
  a184=(a184*a179);
  a189=(a189*a184);
  a20=(a20*a189);
  a131=(a131*a20);
  a196=(a196*a20);
  a131=(a131+a196);
  a196=(a11*a20);
  a130=(a130*a196);
  a131=(a131+a130);
  a194=(a194*a20);
  a131=(a131+a194);
  a20=(a11*a20);
  a62=(a62*a20);
  a131=(a131+a62);
  a11=(a11*a20);
  a126=(a126*a11);
  a131=(a131+a126);
  a126=(a189/a24);
  a123=(a123*a126);
  a193=(a193*a126);
  a123=(a123+a193);
  a193=(a49*a126);
  a121=(a121*a193);
  a123=(a123+a121);
  a191=(a191*a126);
  a123=(a123+a191);
  a126=(a49*a126);
  a190=(a190*a126);
  a123=(a123+a190);
  a49=(a49*a126);
  a116=(a116*a49);
  a123=(a123+a116);
  a131=(a131+a123);
  a123=(a184/a113);
  a111=(a111*a123);
  a188=(a188*a123);
  a111=(a111+a188);
  a188=(a36*a123);
  a109=(a109*a188);
  a111=(a111+a109);
  a186=(a186*a123);
  a111=(a111+a186);
  a123=(a36*a123);
  a185=(a185*a123);
  a111=(a111+a185);
  a36=(a36*a123);
  a104=(a104*a36);
  a111=(a111+a104);
  a131=(a131+a111);
  a111=(a179/a101);
  a99=(a99*a111);
  a183=(a183*a111);
  a99=(a99+a183);
  a183=(a21*a111);
  a97=(a97*a183);
  a99=(a99+a97);
  a181=(a181*a111);
  a99=(a99+a181);
  a111=(a21*a111);
  a180=(a180*a111);
  a99=(a99+a180);
  a21=(a21*a111);
  a92=(a92*a21);
  a99=(a99+a92);
  a131=(a131+a99);
  a99=(a3/a89);
  a87=(a87*a99);
  a178=(a178*a99);
  a87=(a87+a178);
  a178=(a12*a99);
  a85=(a85*a178);
  a87=(a87+a85);
  a176=(a176*a99);
  a87=(a87+a176);
  a99=(a12*a99);
  a175=(a175*a99);
  a87=(a87+a175);
  a12=(a12*a99);
  a80=(a80*a12);
  a87=(a87+a80);
  a131=(a131+a87);
  a203=(a203+a7);
  a143=(a143*a203);
  a149=(a149*a143);
  a155=(a155*a149);
  a161=(a161*a155);
  a74=(a74*a161);
  a166=(a166*a161);
  a74=(a74+a166);
  a166=(a162*a161);
  a72=(a72*a166);
  a74=(a74+a72);
  a164=(a164*a161);
  a74=(a74+a164);
  a161=(a162*a161);
  a163=(a163*a161);
  a74=(a74+a163);
  a162=(a162*a161);
  a67=(a67*a162);
  a74=(a74+a67);
  a131=(a131-a74);
  a74=(a155/a64);
  a61=(a61*a74);
  a160=(a160*a74);
  a61=(a61+a160);
  a160=(a156*a74);
  a59=(a59*a160);
  a61=(a61+a59);
  a158=(a158*a74);
  a61=(a61+a158);
  a74=(a156*a74);
  a157=(a157*a74);
  a61=(a61+a157);
  a156=(a156*a74);
  a54=(a54*a156);
  a61=(a61+a54);
  a131=(a131-a61);
  a61=(a149/a51);
  a48=(a48*a61);
  a154=(a154*a61);
  a48=(a48+a154);
  a154=(a150*a61);
  a46=(a46*a154);
  a48=(a48+a46);
  a152=(a152*a61);
  a48=(a48+a152);
  a61=(a150*a61);
  a151=(a151*a61);
  a48=(a48+a151);
  a150=(a150*a61);
  a41=(a41*a150);
  a48=(a48+a41);
  a131=(a131-a48);
  a48=(a143/a38);
  a35=(a35*a48);
  a148=(a148*a48);
  a35=(a35+a148);
  a148=(a144*a48);
  a33=(a33*a148);
  a35=(a35+a33);
  a146=(a146*a48);
  a35=(a35+a146);
  a48=(a144*a48);
  a145=(a145*a48);
  a35=(a35+a145);
  a144=(a144*a48);
  a28=(a28*a144);
  a35=(a35+a28);
  a131=(a131-a35);
  a35=(a203/a25);
  a19=(a19*a35);
  a142=(a142*a35);
  a19=(a19+a142);
  a142=(a138*a35);
  a17=(a17*a142);
  a19=(a19+a17);
  a140=(a140*a35);
  a19=(a19+a140);
  a35=(a138*a35);
  a139=(a139*a35);
  a19=(a19+a139);
  a138=(a138*a35);
  a9=(a9*a138);
  a19=(a19+a9);
  a131=(a131-a19);
  a137=(a137*a170);
  a201=(a201*a172);
  a137=(a137+a201);
  a201=(a137/a79);
  a135=(a135+a135);
  a173=(a173/a79);
  a173=(a173*a137);
  a136=(a136/a79);
  a171=(a171*a172);
  a174=(a174*a170);
  a171=(a171-a174);
  a136=(a136*a171);
  a173=(a173+a136);
  a136=(a79+a79);
  a173=(a173/a136);
  a135=(a135*a173);
  a201=(a201-a135);
  a91=(a91*a201);
  a103=(a103*a91);
  a115=(a115*a103);
  a125=(a125*a115);
  a16=(a16*a125);
  a128=(a128*a125);
  a16=(a16+a128);
  a127=(a127*a125);
  a8=(a8*a127);
  a16=(a16+a8);
  a131=(a131+a16);
  a16=10.;
  a23=(a23/a24);
  a195=(a195*a189);
  a129=(a129*a115);
  a195=(a195+a129);
  a23=(a23*a195);
  a192=(a192/a24);
  a192=(a192*a189);
  a23=(a23-a192);
  a120=(a120/a24);
  a120=(a120*a115);
  a23=(a23-a120);
  a124=(a124*a23);
  a124=(a16*a124);
  a131=(a131+a124);
  a115=(a115/a24);
  a122=(a122*a115);
  a119=(a119*a115);
  a122=(a122+a119);
  a118=(a118*a115);
  a117=(a117*a118);
  a122=(a122+a117);
  a131=(a131+a122);
  a114=(a114/a113);
  a197=(a197*a184);
  a132=(a132*a103);
  a197=(a197+a132);
  a114=(a114*a197);
  a187=(a187/a113);
  a187=(a187*a184);
  a114=(a114-a187);
  a108=(a108/a113);
  a108=(a108*a103);
  a114=(a114-a108);
  a112=(a112*a114);
  a112=(a16*a112);
  a131=(a131+a112);
  a103=(a103/a113);
  a110=(a110*a103);
  a107=(a107*a103);
  a110=(a110+a107);
  a106=(a106*a103);
  a105=(a105*a106);
  a110=(a110+a105);
  a131=(a131+a110);
  a102=(a102/a101);
  a198=(a198*a179);
  a133=(a133*a91);
  a198=(a198+a133);
  a102=(a102*a198);
  a182=(a182/a101);
  a182=(a182*a179);
  a102=(a102-a182);
  a96=(a96/a101);
  a96=(a96*a91);
  a102=(a102-a96);
  a100=(a100*a102);
  a100=(a16*a100);
  a131=(a131+a100);
  a91=(a91/a101);
  a98=(a98*a91);
  a95=(a95*a91);
  a98=(a98+a95);
  a94=(a94*a91);
  a93=(a93*a94);
  a98=(a98+a93);
  a131=(a131+a98);
  a90=(a90/a89);
  a199=(a199*a3);
  a134=(a134*a201);
  a199=(a199+a134);
  a90=(a90*a199);
  a177=(a177/a89);
  a177=(a177*a3);
  a90=(a90-a177);
  a84=(a84/a89);
  a84=(a84*a201);
  a90=(a90-a84);
  a88=(a88*a90);
  a88=(a16*a88);
  a131=(a131+a88);
  a201=(a201/a89);
  a86=(a86*a201);
  a83=(a83*a201);
  a86=(a86+a83);
  a82=(a82*a201);
  a81=(a81*a82);
  a86=(a86+a81);
  a131=(a131+a86);
  a171=(a171/a79);
  a78=(a78+a78);
  a78=(a78*a173);
  a171=(a171-a78);
  a27=(a27*a171);
  a40=(a40*a27);
  a53=(a53*a40);
  a66=(a66*a53);
  a73=(a73*a66);
  a70=(a70*a66);
  a73=(a73+a70);
  a69=(a69*a66);
  a68=(a68*a69);
  a73=(a73+a68);
  a131=(a131+a73);
  a159=(a159/a64);
  a159=(a159*a155);
  a65=(a65/a64);
  a165=(a165*a155);
  a71=(a71*a53);
  a165=(a165-a71);
  a65=(a65*a165);
  a159=(a159-a65);
  a58=(a58/a64);
  a58=(a58*a53);
  a159=(a159-a58);
  a63=(a63*a159);
  a63=(a16*a63);
  a131=(a131+a63);
  a53=(a53/a64);
  a60=(a60*a53);
  a57=(a57*a53);
  a60=(a60+a57);
  a56=(a56*a53);
  a55=(a55*a56);
  a60=(a60+a55);
  a131=(a131+a60);
  a153=(a153/a51);
  a153=(a153*a149);
  a52=(a52/a51);
  a167=(a167*a149);
  a75=(a75*a40);
  a167=(a167-a75);
  a52=(a52*a167);
  a153=(a153-a52);
  a45=(a45/a51);
  a45=(a45*a40);
  a153=(a153-a45);
  a50=(a50*a153);
  a50=(a16*a50);
  a131=(a131+a50);
  a40=(a40/a51);
  a47=(a47*a40);
  a44=(a44*a40);
  a47=(a47+a44);
  a43=(a43*a40);
  a42=(a42*a43);
  a47=(a47+a42);
  a131=(a131+a47);
  a147=(a147/a38);
  a147=(a147*a143);
  a39=(a39/a38);
  a168=(a168*a143);
  a76=(a76*a27);
  a168=(a168-a76);
  a39=(a39*a168);
  a147=(a147-a39);
  a32=(a32/a38);
  a32=(a32*a27);
  a147=(a147-a32);
  a37=(a37*a147);
  a37=(a16*a37);
  a131=(a131+a37);
  a27=(a27/a38);
  a34=(a34*a27);
  a31=(a31*a27);
  a34=(a34+a31);
  a30=(a30*a27);
  a29=(a29*a30);
  a34=(a34+a29);
  a131=(a131+a34);
  a141=(a141/a25);
  a141=(a141*a203);
  a26=(a26/a25);
  a169=(a169*a203);
  a77=(a77*a171);
  a169=(a169-a77);
  a26=(a26*a169);
  a141=(a141-a26);
  a15=(a15/a25);
  a15=(a15*a171);
  a141=(a141-a15);
  a22=(a22*a141);
  a16=(a16*a22);
  a131=(a131+a16);
  a171=(a171/a25);
  a18=(a18*a171);
  a14=(a14*a171);
  a18=(a18+a14);
  a13=(a13*a171);
  a10=(a10*a13);
  a18=(a18+a10);
  a131=(a131+a18);
  if (res[1]!=0) res[1][6]=a131;
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_0_fun_jac(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_0_fun_jac_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_0_fun_jac_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_0_fun_jac_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_0_fun_jac_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_0_fun_jac_release(int mem) {
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_0_fun_jac_incref(void) {
}

CASADI_SYMBOL_EXPORT void Solver_cost_ext_cost_0_fun_jac_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Solver_cost_ext_cost_0_fun_jac_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int Solver_cost_ext_cost_0_fun_jac_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real Solver_cost_ext_cost_0_fun_jac_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_cost_ext_cost_0_fun_jac_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Solver_cost_ext_cost_0_fun_jac_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_cost_ext_cost_0_fun_jac_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Solver_cost_ext_cost_0_fun_jac_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Solver_cost_ext_cost_0_fun_jac_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
